name = "starter-auth"
main = "src/auth.ts"
compatibility_date = "2024-01-29"

workers_dev = false
routes = [
    { pattern = "starterapp.work", custom_domain = true }
]

services = [
    { binding = "APP", service = "starter-app" },
]

[dev]
port = 8788
